### ISSUE TITLE
Help me fix this issue

### ISSUE THREAD

**Issue by MrTimonM** [Alexell/MuskEmpireBot#113] opened 2024-09-07 15:24 UTC
I am getting this issue, 
Please note that, my API hash is incorrect because i will use sessions. 
Screenshot : https://ibb.co.com/9YMcyyS

I have few sessions, and can you check if the .env file is correct? I do not get a full guide to edit. 
Thanks

**Comment by NamasteIndia** [comment] 2024-09-08 04:35
> I am getting this issue, Please note that, my API hash is incorrect because i will use sessions. Screenshot : https://ibb.co.com/9YMcyyS
> 
> I have few sessions, and can you check if the .env file is correct? I do not get a full guide to edit. Thanks

Dude! please fix the .env you need to place the correct API_ID and API_HASH the rest can be left blank

API_ID=MANDATORY
API_HASH=MANDATORY

TAPS_ENABLED=
TAPS_PER_SECOND=
INVEST_ENABLED=
PVP_ENABLED=
PVP_LEAGUE=
PVP_UPGRADE_LEAGUE=
PVP_STRATEGY=
PVP_COUNT=
SKILLS_COUNT=
SKILLS_MODE=
IGNORED_SKILLS=
MINING_SKILLS_LEVEL=
PROTECTED_BALANCE=
DAY_MAIN_DELAY=
NIGHT_MAIN_DELAY=
REF_CODE=

SLEEP_BETWEEN_START=
ERRORS_BEFORE_STOP=
USE_PROXY_FROM_FILE=
DEBUG_MODE=

The rest can be left Blank, It doesnt matters if you using 1 session or 69 sessions. Just set any ONE accounts API_ID, API_HASH and you are done

**Comment by Alexell** [comment] 2024-09-08 09:34
@MrTimonM If the issue is resolved, close the issue. If not, upload the screenshot directly to the comment form, and not to a third-party service where the link does not work.

**Closed as completed** 2024-09-08 09:37 UTC
